name: Install Node and Run Code


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
        runs-on: [self-hosted, testing-self-hosted]
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        
        - name: Install Node
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
        
        - name: Run Code
          run: |
            npm install
            npm run start
            echo "Code has been run"