name: "Demo NodeJS Action"

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  silent-failure-issue:
    runs-on: [self-hosted, linux]
    steps:

      - uses: actions/checkout@v3

      - name: Install ZSTD dependency
        run: sudo apt-get install -y zstd
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com/
          always-auth: false
          check-latest: false

      - name: Install dependencies
        run: yarn install

      - name: Show Node Version
        run: node --version